# Generated by Django 2.1.3 on 2018-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('star', models.IntegerField()),
                ('min_order_amount', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('payment', models.BooleanField()),
                ('estimated_delivery_time', models.CharField(max_length=20)),
                ('additional_discount_per_menu', models.IntegerField()),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
    ]
