# Generated by Django 2.1.3 on 2018-12-06 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='restaurant/food')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food', models.ManyToManyField(blank=True, to='restaurants.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='restaurant')),
                ('review_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.IntegerField()),
                ('except_cash', models.BooleanField(default=True)),
                ('review_count', models.IntegerField()),
                ('owner_reply_count', models.IntegerField()),
                ('estimated_delivery_time', models.CharField(max_length=20)),
                ('discount_percent', models.IntegerField()),
                ('additional_discount_per_menu', models.IntegerField()),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('company_name', models.CharField(max_length=50)),
                ('company_number', models.CharField(max_length=20)),
                ('country_origin', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(blank=True, to='restaurants.Category')),
                ('payment_methods', models.ManyToManyField(blank=True, to='restaurants.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('rating_delivery', models.DecimalField(decimal_places=1, max_digits=10)),
                ('rating_quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('rating_taste', models.DecimalField(decimal_places=1, max_digits=10)),
                ('review_images', models.ImageField(blank=True, null=True, upload_to='restaurant/review')),
                ('time', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('food', models.ManyToManyField(blank=True, to='restaurants.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='restaurants.Tag'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
