# Generated by Django 2.1.3 on 2018-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181201_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='logo',
            new_name='logo_url',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='payment',
            field=models.BooleanField(default=True),
        ),
    ]
