# Generated by Django 2.1.3 on 2018-12-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181206_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country_origin',
            field=models.CharField(max_length=500),
        ),
    ]
