# Generated by Django 2.1.3 on 2018-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181219_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country_origin',
            field=models.CharField(max_length=20000),
        ),
    ]
