# Generated by Django 2.1.3 on 2018-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20181201_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant'),
        ),
    ]
