# Generated by Django 2.1.3 on 2018-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_food_menu_subchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subchoice',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
