# Generated by Django 2.1.3 on 2018-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20181206_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='introduction_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
