# Generated by Django 2.1.3 on 2018-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20181205_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='restaurant/food'),
        ),
    ]
