# Generated by Django 2.1.3 on 2018-12-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20181208_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
