# Generated by Django 2.1.3 on 2018-11-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
