# Generated by Django 2.1.3 on 2018-12-28 06:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20181228_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+820100000000', max_length=128),
        ),
    ]
